### ISSUE TITLE
Implement yaml profiles

### ISSUE THREAD

**Issue by oxr463** [oxr463/quickstart#8]
Example taken from man page:

```yml
---
stage_uri: http://192.168.0.12/gentoo/stage3-i686-2006.1.tar.bz2
tree_type:
  type: snapshot
  uri: http://192.168.0.12/gentoo/portage-20061216.tar.bz2
rootpw: password
bootloader: grub

part:
  drive: hda
  minor: 1
  type: 83
  size: 100M
part:
  drive: hda
  minor: 2
  type: 82
  size: 512M
part:
  drive: hda
  minor: 3
  type: 83
  size: +

format:
  device: /dev/hda1
  fs: ext2
format:
  device: /dev/hda2
  fs: swap
format:
  device: /dev/hda3
  fs: ext3

mountfs:
  device: /dev/hda1
  type: ext2
  mountpoint: /boot
mountfs:
  device: /dev/hda2
  type: swap
mountfs:
  device: /dev/hda3
  type: ext3
  mountpoint: /
  mountopts: noatime

net:
  device: eth0
  ip: dhcp

netmount:
  export: 192.168.0.12:/usr/portage
  type: nfs
  mountpoint: /usr/portage
  mountopts: ro

post_install_portage_tree: |
  cat > ${chroot_dir}/etc/make.conf <<EOF
  CHOST="i686-pc-linux-gnu"
  CFLAGS="-O2 -march=athlon-xp -pipe"
  CXXFLAGS="\${CFLAGS}"
  USE="-X -gtk -gnome -kde -qt"
  EOF
  echo "portdbapi.auxdbmodule = cache.metadata_overlay.database" \
    > ${chroot_dir}/etc/portage/modules
```
See: https://github.com/yaml/libyaml/issues/147
